### ISSUE TITLE
lint Errors (InvalidPackage: Package not included in Android)

### ISSUE THREAD

**Issue by andreya108** [tony19/logback-android#113]
com.github.tony19/logback-android-core/1.1.1-4/cd422166cca6c3d930309a6685ea3f40c91942ce/logback-android-core-1.1.1-4.jar: Invalid package reference in library; not included in Android: javax.mail.internet. Referenced from ch.qos.logback.core.net.SMTPAppenderBase.

com.github.tony19/logback-android-core/1.1.1-4/cd422166cca6c3d930309a6685ea3f40c91942ce/logback-android-core-1.1.1-4.jar: Invalid package reference in library; not included in Android: javax.mail. Referenced from ch.qos.logback.core.net.LoginAuthenticator.

ps: do you plan to merge recent code from qos-ch? It has new must-have features (for example SizeAndTimeBasedRollingPolicy).

**Comment by tony19** [comment]
That's currently by design. If your app requires the `SMTPAppender`, you must provide the appropriate jars for the `javax.mail` package (as documented in the [Wiki][1]). It's admittedly a clunky requirement inherited from the original logback project, and I'm thinking of breaking that appender out into its own add-on.

Yes, I do plan to sync logback-android with the latest changes in the coming weeks.

 [1]: https://github.com/tony19/logback-android/wiki/Appender-Notes#smtpappender

**Comment by tony19** [comment]
It looks like Oracle released `android-mail`. I confirmed that adding these dependencies clears the lint errors:

```groovy
dependencies {
    compile 'com.sun.mail:android-mail:1.5.5'
    compile 'com.sun.mail:android-activation:1.5.5'
}
```
