### ISSUE TITLE
Programatically configuring logging

### ISSUE THREAD

**Issue by skyflyer** [tony19/logback-android#118]
I'd like to programatically configure the logging subsystem; I see that the newer versions of logback support this: [4. If no such file is found, service-provider loading facility (introduced in JDK 1.6) is used to resolve...](http://logback.qos.ch/manual/configuration.html)

Are there any plans to move forward with tracking the newer versions or is there another option that I missed?

I'm not sure how much work is involved in updating to a current version, but perhaps I could help?

**Comment by tony19** [comment]
You can already programmatically configure logging with the current versions of `logback-android`. The service-provider loading feature is not needed to do that. (And btw, that feature will not be ported to `logback-android`).

I've started the upstream merge in the [integration/upstream branch](https://github.com/tony19/logback-android/tree/integration/upstream), and I've fixed most of the integration issues except for a few broken unit tests. Unfortunately, I have no time to debug it, and I've hesitated because there are some regressions upstream (based on feedback on the mailing list and in JIRA). I would definitely appreciate the help in the integration.

**Comment by skyflyer** [comment]
Tony, thanks for responding so quickly!

I'll check the referenced branch and see if I can be of any assistance.
