### ISSUE TITLE
TotalSizeCap does not work.

### ISSUE THREAD

**Issue by luquettacwb** [tony19/logback-android#126]
Hi,

I set totalSizeCap in logback.xml like this:

`
...
<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${LOG_DIR}/my_app_name.%d{yyyy-MM-dd}.log.zip</fileNamePattern>
            <maxHistory>45</maxHistory>
            <totalSizeCap>1MB</totalSizeCap>
 </rollingPolicy>
...
`

But after 1MB size of logs the olds don't be erased.

**Comment by tony19** [comment]
`logback-android` currently does not support that feature. `logback` added `<totalSizeCap>` in [1.1.7](https://github.com/qos-ch/logback/blob/03e26684d43066d53dbf926e060a73d43bee77fd/logback-site/src/site/pages/news.html#L79), while `logback-android` is still based on 1.1.1. I started an upstream merge a while ago in the [integration/upstream](https://github.com/tony19/logback-android/tree/integration/upstream) branch, but it fails several unit tests, so it's unstable.

**Comment by schildbach** [comment]
It would be great if logback-android would support totalSizeCap. I have a case where my app mysteriously created gigabytes of logs and it's even so big that the user can't use my email reporter to sent it to me. A total size cap would fix this at least so that I can see a bit of the log to fix the cause of the issue.
