### ISSUE TITLE
Missing 1.1.1-6 and 1.1.1-5 in jcenter now

### ISSUE THREAD

**Issue by guohai** [tony19/logback-android#142]
The latest version is 1.1.1-4 so far, some time ago, there is still have 1.1.1-5, but so far it is gone.

![image](https://cloud.githubusercontent.com/assets/436781/24493907/06e4e60e-1563-11e7-946d-3803b95f5f2e.png)

**Comment by JonasVautherin** [comment]
In the meantime, note that it is on mvnrepository.com, just in case you need it: 

https://mvnrepository.com/artifact/com.github.tony19/logback-android-classic
https://mvnrepository.com/artifact/com.github.tony19/logback-android-core

**Comment by tony19** [comment]
I'm not sure why jcenter is not sync'ed with Maven Central (where the packages are already published). I've contacted JFrog for assistance.

**Comment by tony19** [comment]
The issue is after claiming ownership of the repo in JCenter, the version management must be then handled by the owner. JCenter doesn't automatically sync its version info with Maven Central. Our deployment process needs to change so that it deploys to JCenter, and then manually synced from JCenter to Maven Central (but perhaps there's a way to automate this).

**Comment by tony19** [comment]
Newer versions are now available in jcenter.
