### ISSUE TITLE
RollingFileAppender is not rolling :-)

### ISSUE THREAD

**Issue by HowardSchmaeu** [tony19/logback-android#203]
i try to use the RollingFileAppender and i also read every sample i found but it is not rolling it only creates one File..

`       
        String loggername  = "MyLogger";
        String logFileName = "mylogger";
        logFile = LogHelper.LOG_FOLDER + "/" + logFileName +".log";

        LoggerContext lc = (LoggerContext) LoggerFactory.getILoggerFactory();

        // setup FileAppender
        PatternLayoutEncoder encoder1 = new PatternLayoutEncoder();
        encoder1.setContext(lc);
        encoder1.setPattern("%d{dd.MM.yyyy HH:mm:ss.SSS} \t [%logger{0}] \t %msg%n");
        encoder1.start();

        RollingFileAppender<ILoggingEvent> rollingFileAppender = new RollingFileAppender<>();
        rollingFileAppender.setContext(lc);
        rollingFileAppender.setName(loggername);
        rollingFileAppender.setEncoder(encoder1);
        rollingFileAppender.setAppend(true);
        rollingFileAppender.setFile(logFile);

        TimeBasedRollingPolicy<ILoggingEvent> rollingPolicy = new TimeBasedRollingPolicy<>();
        rollingPolicy.setContext(lc);
        rollingPolicy.setParent(rollingFileAppender);  // parent and context required!
        rollingPolicy.setFileNamePattern(logFileName + ".%d{yyyy-MM-dd}.zip");
        rollingPolicy.setMaxHistory(5); // no more than n rollover files (delete oldest)
        rollingPolicy.setTotalSizeCap(FileSize.valueOf("50KB"));
        rollingPolicy.start();

        rollingFileAppender.setRollingPolicy(rollingPolicy);

        SizeBasedTriggeringPolicy sizeBasedTriggeringPolicy = new SizeBasedTriggeringPolicy();
        sizeBasedTriggeringPolicy.setContext(lc);
        sizeBasedTriggeringPolicy.setMaxFileSize(FileSize.valueOf("50KB"));
        sizeBasedTriggeringPolicy.start();

        rollingFileAppender.setTriggeringPolicy(sizeBasedTriggeringPolicy);

        rollingFileAppender.start();

        Logger root = (Logger) LoggerFactory.getLogger(loggername);
        root.detachAndStopAllAppenders();
        root.addAppender(rollingFileAppender);
        root.addAppender(logcatAppender);

        lc.start();`

**Comment by tony19** [comment]
I can't determine the problem from your config code alone.

Can you provide a sample repo (in GitHub) and reproduction steps?

**Comment by HowardSchmaeu** [comment]
Okay i've upload a test Project to [here](https://github.com/HowardSchmaeu/SpikeLoggerTest) If you need more please let me know

**Comment by tony19** [comment]
The problem turns out to be in your config.

* Using `TimeBasedRollingPolicy` and `SizeBasedTriggeringPolicy` results in an exception similar to the one seen in [LOGBACK-995](https://jira.qos.ch/browse/LOGBACK-995). Instead, use [`SizeAndTimeBasedRollingPolicy`](https://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy) for the rolling policy. Note that it also serves as a triggering policy, so you don't need to add one.

* The [filename pattern is relative](https://github.com/HowardSchmaeu/SpikeLoggerTest/blob/master/app/src/main/java/com/example/loggertest/Z1Logger.java#L65) when it should be an absolute path. From [[1]](https://github.com/tony19/logback-android/wiki/Appender-Notes#fileappender-rollingfileappender):

> Use absolute paths to a file destination where your application has write-permissions, such as `/data/data/<packagename>/files/`.

Check out the changes I've made in https://github.com/HowardSchmaeu/SpikeLoggerTest/pull/1.

**Comment by HowardSchmaeu** [comment]
THX soooo much ... now it's rolling and working !!!
