### ISSUE TITLE
Rolling over is not working as expected.

### ISSUE THREAD

**Issue by pramodrapolu** [tony19/logback-android#207]
I used the repo which is created to fix part of the issue https://github.com/tony19/logback-android/issues/203

## Description
So I used same configuration as there and I am seeing 1st file going till 62 kb and rest of files around 3-4 kb.
It's not rolling over properly.

## Steps to reproduce
took the repo mentioned in the issue above, clicked on the fab to generate logs, looked in to file system for the size and it was 62 kb and clicked the fab again and the file size was 4 kb and so on.

And another thing is max history was given 5 but the generated files were above 5.

Please look at the screen shot for the files generated.

Note: The only thing I changed in the code was the path of the files where it saves. I used below inside the configureLogbackDirectly method,

String loggername  = "Z1 Logger";
        File file = context.getExternalFilesDir("logs");
        String logFileName = null;
        if (file != null) {
            logFileName = file.getAbsolutePath() + "/z1-myLogger";
        } else {
            Log.d("Blah", "file is null");
        }
        logFile = logFileName + ".log";

## Environment

* **`logback-android` version: 2.0.0**
* **Android version:*8.0.0*
* **Platform: Samsung s8
![Screen Shot 2019-10-23 at 7 57 12 PM](https://user-images.githubusercontent.com/17262588/67442699-f0e3b100-f5cf-11e9-9e80-b5bc71019a42.png)
**

**Comment by tony19** [comment]
This seems to work as designed. I think there might be a misunderstanding in the config, so let me explain:

 * `maxHistory` pertains to the number of *periods* archived (not number of files). The date pattern in the filename is `%d{yyyy-MM-dd}`, which creates a **daily** period, so `maxHistory` specifies *number of days* in this case. Therefore, a `maxHistory` of 5 indicates that files older than 5 days would be deleted.

 * `maxFileSize` is the maximum file size *before* compression. If you decompress the `.zip` files, you'll see that they're just under 50KB, which matches the configuration.

 * `totalSizeCap` refers to the cummulative size of all archive files (i.e., the `.zip` files in this case). Each 50KB file zips up to ~3.8KB, which gives us a maximum of 13 `.zip` files for a `totalSizeCap` of 50KB. You'll notice that clicking the FAB repeatedly never results in more than 13 `.zip`s.

Regarding the 62KB size of the active log file: this is a known issue. `logback` throttles file-size checks in order to improve overall logging performance (especially in busy logging environments), but this unfortunately results in fewer than expected log rotations as a side effect. This throttle will be removed in the next release.

**Comment by pramodrapolu** [comment]
@tony19 Thanks for the reply! So for me to rollover based on just size and delete the old files, what would be the best way to configure? or do I handle it custom way?

**Comment by pramod-kumar-rapolu-bose** [comment]
@tony19 Never mind. I think I have to use FixedWindowRollingPolicy and SizeBasedTriggeringPolicy for that in case of just rolling over based on size and limiting the number of files.

**Comment by pramodrapolu** [comment]
@tony19 Never mind. I think I have to use FixedWindowRollingPolicy and SizeBasedTriggeringPolicy for that in case of rolling over based on just size and limiting the number of files.
