### ISSUE TITLE
Logback with Encryption is not writing all the data.

### ISSUE THREAD

**Issue by pramodrapolu** [tony19/logback-android#210]
I have written a custom rolling file appender, where I overrode `setOutputStream()`, and I'm trying to encrypt the output stream, as shown below (highlighted).

My custom rolling appender class:

```kotlin
class CustomRollingFileAppender<E> constructor(context: Context) : RollingFileAppender<E>() {
   
    val logProcessor: LogProcessor

    init {
        logProcessor = LogProcessor(context)
    }

    override fun setOutputStream(outputStream: OutputStream) {
        synchronized(lock) {         
            if (outputStream is ResilientFileOutputStream) {
                val cos: CipherOutputStream = logProcessor.encrypt(outputStream)
                super.setOutputStream(cos)
            } else {
                super.setOutputStream(outputStream)
            }
        }
    }
}
```

I have the below method which generates a key from keystore, creates a cipher, and returns a cipher output stream, which would be set in the above implementation.

```kotlin
    fun encrypt(outputStream: OutputStream): CipherOutputStream {
        val cipher = Cipher.getInstance("AES/CBC/PKCS7Padding")
        cipher.init(Cipher.ENCRYPT_MODE, keyFromKeystore)

        return CipherOutputStream(outputStream, cipher)
    }
```

But what I observed was if I try to log like around 1000 lines of data as soon as I clicked a button as below, it is not entirely writing the data in to the files. I found this out when I decrypted the file back. 

```kotlin
    private void createLoggerEntrys() {
        for (int i = 1; i < 1000; i++){
            logger.debug("i have entry #[{}]",i);
        }
    }
```

However if I use 30 lines of data for example after I click a button, it is working good. I was able to encrypt and decrypt it back with all the data entered.

I did set immediate flush to my encoder which is going to be used as flag to flush the bytes to underlying output stream.

Can you please guide/clarify on this? Let me know if you have any questions on this.

**Comment by pramodrapolu** [comment]
@tony19 Can you please help me on this?

**Comment by tony19** [comment]
Can you provide a link to a GitHub repo that reproduces the problem?

**Comment by pramodrapolu** [comment]
Hey Tony, thanks for the reply. Here is the link https://github.com/pramodrapolu/loggertest

Let me know if you have any questions. Thanks again!

**Comment by tony19** [comment]
Thanks for the repro. I was able to reproduce the issue.

A couple notes:
 * While this wasn't the root cause, the `immediateFlush` wasn't taking effect in your code because the encoder was started before assigning a parent. The encoder's `immediateFlush` property is deprecated in any case, so the parent appender's `immediateFlush` should be set instead (i.e., `fileAppender.setImmediateFlush(true)`).

 * It seems the root problem is that the log entry buffer/queue in `AsyncAppender` is not large enough for your use case (by default, it can buffer about 200 log entries). If the buffer is filled faster than it could be processed (perhaps caused by the time it takes to encrypt the previous log entry), newer log entries get discarded. The following settings resolved the missing log entries in my tests:

```java
asyncAppender.setQueueSize(1000); // default is 256
asyncAppender.setDiscardingThreshold(0); // default is 51 (I don't know its original purpose)
```

Let me know if this works for you.

**Comment by pramodrapolu** [comment]
@tony19  Thanks for the reply. Looks like this is working.
So this immediate flush is the one which takes care of writing the bytes to underlying output stream correct? And if I increase that buffer are there any side effects with it that I should be aware of?

One more question I had was, so after these encrypted files are created, I was trying to decrypt the active file which is still open stream I guess. 
When I am trying to decrypt that it is throwing some exceptions.
So, Is there any best way that you could suggest that I could go with to decrypt the active file? Right now in the repo I have provided I have been trying to decrypt the rolled over file, if you want to test that you can replace the rolled over file name ("my-log-1" with "my-log")

One option/solution I was thinking of was manually rolling over and use the rolled over file to decrypt, is there any way that you could suggest that is efficient than that? 

Thanks in advance.

**Comment by tony19** [comment]
> And if I increase that buffer are there any side effects with it that I should be aware of?

No other known side effects other than increased memory usage.

> And also do I handle anything specific with logback for it to write the bytes which that buffer hold just before closing the app?

No action on your part is necessary because the default shutdown hook (see ["Post shutdown cleanup"](http://logback.qos.ch/manual/appenders.html#AsyncAppender)) automatically stops the `AsyncAppender`, which flushes the buffer.

>  or that immediate flush takes care of doing that?

No, `immediateFlush` applies to the `FileAppender` in this case (not `AsyncAppender`).

> One option/solution I was thinking of was manually rolling over and use the rolled over file to decrypt, is there any way that you could suggest that is efficient than that?

Sorry, I can't offer any better suggestions than that.

**Comment by pramodrapolu** [comment]
@tony19 Got it and no worries Thanks for the help! (Y)

**Comment by pramodrapolu** [comment]
@tony19 Hey Tony, So just to confirm if I use the setting `immediateFlush` to fileAppender, does it makes sense for me to add `queueSize` value? Immediate flush should be writing everything as it gets to underlying output stream so `queueSize` doesn't have any effect in that case correct?

**Comment by tony19** [comment]
The larger `queueSize` and `discardingThreshold=0` are needed in your use case.

The `immediateFlush` flag doesn't really address the root problem, which is that log entries are not reaching the `FileAppender`; not that the appender isn't flushing them in time. Before log entries can even get to the `FileAppender`, they're buffered in the `AsyncAppender`'s queue.
