### ISSUE TITLE
No log is printed with Slf4j 2.x.x

### ISSUE THREAD

**Issue by toantk238** [tony19/logback-android#249]
## Description

I apply the slf4j version 2.0.3 in android project.
I tried to print log with debug, error level but nothing is printed. I check via logcat.

If I rollback to version 1.7.36, it works.

## Steps to reproduce

implementation("org.slf4j:slf4j-api:2.0.3")
implementation("com.github.tony19:logback-android:2.0.0")

## Environment

Android version : 9
Device : Huawei Nova 3i

**Comment by Sin4th** [comment]
We have the same problem in our app, just after upgrading to Android target sdk 33 and setting both source- and targetCompatibility to JDK 11. After a bit of deep diving we noticed the following:

* Xml file was not read and logger fell back into NOPLogger implementation
* This was also the case when creating a logger via programmatic approach
* Already the call `LoggerFactory.getILoggerFactory()` produced a NOPLoggerFactory

Same thing happens when trying to use the original logback dependencies without the logback-android one like this:

`
    implementation 'ch.qos.logback:logback-classic:1.2.3'
    implementation 'ch.qos.logback:logback-core:1.2.6'
    implementation 'ch.qos.logback:logback-parent:1.2.6'
`

This makes me believe that there is a general incompatibility wiith either Android 13 or Java 11 in the core libraries. I will research further and if necessary create a ticket for ch.qos.logback. If so, i will link it here.

**Comment by tony19** [comment]
This should be fixed by #247, expected in [next major release](https://github.com/tony19/logback-android/milestone/21).

**Comment by JAYP1255** [comment]
#247

**Comment by JAYP1255** [comment]
Thanks

**Comment by schildbach** [comment]
> This should be fixed by #247, expected in [next major release](https://github.com/tony19/logback-android/milestone/21).

Just for clarification, 2.0.1 istn't that "next major release" – right?

**Comment by tony19** [comment]
@schildbach Correct. 3.0.0 is the next major release. I was prepared to release 3.0.0 with #247, but it caused build issues, so I reverted it for now until we can get that fixed.

**Comment by conbrad** [comment]
We're also affected by this issue. I noticed the major release linked above has no specific date, would you be open to cutting that release sooner than later?

**Comment by tony19** [comment]
Fix is released in [v3.0.0](https://github.com/tony19/logback-android/releases/tag/v_3.0.0). It may take a while before it's indexed in Maven Central.

**Comment by conbrad** [comment]
> Fix is released in [v3.0.0](https://github.com/tony19/logback-android/releases/tag/v_3.0.0). It may take a while before it's indexed in Maven Central.

Thank you!

**Comment by sorinirimies** [comment]
Thank you so much.
