### ISSUE TITLE
Is there a way to save log files on the external storage just by using configuration XML?

### ISSUE THREAD

**Issue by mclovin-2k** [tony19/logback-android#62]
Since API level 19, you don't need any permission to read/write files in your application-specific directories returned by getExternalFilesDir(String) and getExternalCacheDir(), so I want to save my log files into those directories. But the path of application-specific external directories can be every different on all kinds of android devices. And I don't want to set appender's file path in java code. Can I do it in XML configuration file, and how?

**Comment by nateridderman** [comment]
Thanks, this was helpful!

**Comment by yozh1k** [comment]
Thanks, its work. But there is another problem: if log file was deleted(e.g. via file manager) it will be recreated only after apk reinstall. Is there any solution for this problem?

**Comment by luktar** [comment]
This solution was working on my android 4.3. Now I have Android 7 and it doesn't work at all.
`05-01 12:40:36.576 3522-3522/com.xxx I/System.out: 12:40:36,551 |-ERROR in ch.qos.logback.core.FileAppender[file] - Failed to create parent directories for [/storage/emulated/0/Android/data/com.xxx/files/log/log.txt]
05-01 12:40:36.576 3522-3522/com.xxx I/System.out: 12:40:36,559 |-ERROR in ch.qos.logback.core.FileAppender[file] - openFile(/storage/emulated/0/Android/data/com.xxx/files/log/log.txt,true) failed java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.xxx/files/log/log.txt: open failed: ENOENT (No such file or directory)`

**Comment by dmayle** [comment]
As of Android API 18, you no longer need the permission WRITE_EXTERNAL_STORAGE to create files in the external directory, but you still need that permission to create that directory (or any subdirectories).  Instead of making a permission request, I changed the app to call getExternalFilesDir(null) on startup (in my application class), which causes the OS to create the files directory for you without the permission, and then changed the XML configuration above to use ${EXT_FILES_DIR}  instead of ${EXT_FILES_DIR}/log

**Comment by Sophie713** [comment]
Thank you so much, exactly what I was looking for.
